### ISSUE TITLE
Logging configuration in the input file

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#110]
The logging should be configurable in the input file. The user could specify whether the logging should be send to a file, stdout, stderr or a combination of these. 

We could use the [simplelog](https://docs.rs/simplelog/) crate to provide the logger implementation, and remove the one in `src/core/src/logging.rs`.

I think that default should be to log errors/warnings to stderr and everything else to stdout.

Any idea on how the input file could look like for this?

**Comment by antoinewdg** [comment]
Something like this ?
``` toml
[[loggers]]
name = 'my_file_logger'
type = 'file'
filename = 'logs.txt'

[[loggers]]
name = 'my_stdout_logger'
type = 'stdout'

[[loggers]]
name = 'my_combined_logger'
type = 'combined'
loggers = ['my_stdout_logger', 'my_file_logger']

[log]
error = ['my_file_logger', 'my_stdout_logger']
info = ['my_file_logger']
```

**Comment by Luthaf** [comment]
I don't really like the `name` key here. How about having an inline `level` key, and use an array for the combined case:

```toml
[logger]
type = 'file'
filename = 'logs.txt'
level = "error"

##############

[logger]
type = 'combined'
targets = [  # I don't really like this key name
    {type = 'file', filename = 'logs.txt', level = 'info'},
    {type = 'stdout', level = 'error', color = true},
]
``` 

Or we could even remove the `type` key altogether:

```toml
[logger]
target = 'logs.txt'
level = "error"

##############

[logger]
target = 'stdout'
level = "info"

##############

[logger]
targets = [
    {target = 'logs.txt', level = 'info'},
    {target = 'stdout', level = 'error', color = true},
]
```
