### ISSUE TITLE
Warn on unused keys in the input

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#239]
Because we use TOML as format for the input, the user can add keys that are not used by the input system now:

```toml
[input]
version = 1

[global]
cutoff = {shifted = "10 A"}
shift = true  # This is currently ignored by the code

[[pairs]]
atoms = ["C", "C"]
lj = {sigma = "3.7 A", epsilon = "0.2981 kcal/mol"}
```

We might want to send a warning for all these unused keys, as they might be typos that the user want to correct, or key we might want to use in a future revision of the input files.
