### ISSUE TITLE
Ability to run control algorithm not at all steps

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#31]
Control algorithms like `RemoveRotation` and `RemoveTranslation` do not need to run at each simulation step. they could have separated frequency field to run them only every so often.

**Comment by antoinewdg** [comment]
Is there any docs about how `RemoveRotation` and `RemoveTranslation` should be described in input files ?

**Comment by antoinewdg** [comment]
My bad, [found them](http://lumol-org.github.io/lumol/latest/book/input/md.html).

**Comment by antoinewdg** [comment]
So how should this change be reflected in the TOML file ?
Should there be a `period` key for each control entry ? Should this key be optional ? Default to 1 ?

Or do we just consider that this can not be controlled by the user and set it to a reasonable default ?

**Comment by g-bauer** [comment]
I'd prefer to expose this to the user, but optional. What do you think about this: 

```toml
[simulations.propagator]
type = "MolecularDynamics"
timestep = "1 fs"
thermostat = {type = "Berendsen", temperature = "400 K", timestep = 100}
controls = [
    {type = "RemoveRotation", timestep = 100}
]
```

This would be in line with the thermo- and barostat that also use `timestep` (as factor for the "real" timestep). Now that I am writing this, using two `timestep` could be confusing ...

**Comment by Luthaf** [comment]
> This would be in line with the thermo- and barostat that also use timestep (as factor for the "real" timestep). Now that I am writing this, using two timestep could be confusing.
>
> How about after_steps = 100, steps = 100?

The Monte-Carlo moves uses [`frequency`](https://github.com/lumol-org/lumol/blob/dbe819f52142470b94bce84472ff768fb8da5374/src/input/tests/simulation/good/mc.toml#L15), which I prefer.

**Comment by antoinewdg** [comment]
@g-bauer well I kind of feel that using `timestep` is already super confusing for `Berendsen` and such, since this is not a time step as for the `Propagator`, this is a scaling factor to apply to the `timestep` given to the `Propagator`. 
Maybe this is on account of me not having any background in molecular dynamics, but this felt really confusing. I fist thought it just overrode the `Propagator` `timestep`, is there a particular reason for calling both of them `timestep`? Why not just `tau` as in the code ?

@Luthaf why not `frequency`, this would have to be between 0 and 1 to make sense though, so it would not really be comparable to the `frequency` for MC move, which is an unormalized frequency.

**Comment by Luthaf** [comment]
> @Luthaf why not frequency, this would have to be between 0 and 1 to make sense though, so it would not really be comparable to the frequency for MC move, which is an unormalized frequency.

This should not be between 0 and 1, the user would want to run a specific algorithm every n steps, so the value should be a positive integer. Another possibility here could be `every`, like in 

```toml
[simulations.propagator]
type = "MolecularDynamics"
timestep = "1 fs"
thermostat = {type = "Berendsen", temperature = "400 K", timestep = 100}
controls = [
    {type = "RemoveRotation", every = 100}
]
```

> Maybe this is on account of me not having any background in molecular dynamics, but this felt really confusing. I fist thought it just overrode the Propagator timestep, is there a particular reason for calling both of them timestep? Why not just tau as in the code ?

It is called timestep, because it is actually a timestep in all the litterature, using `tau` in the code is mainly a commodity. But if this is confusing, how about changing the thermostats/barostats timesteps to real timesteps, and compute the value of tau in the code?

```toml
[simulations.propagator]
type = "MolecularDynamics"
timestep = "1 fs"
thermostat = {type = "Berendsen", temperature = "400 K", timestep = "100 fs"}
```
