### ISSUE TITLE
Better testing for bad inputs

### ISSUE THREAD

**Issue by Luthaf** [lumol-org/lumol#42]
Currently, bad input are tested by checking that the result of the input read is an error. But we do not control the source of the error. Allowing to specify the expected error inside the bad input file would guarantee that we do not get another error that the one wanted (bad TOML, IO error, ...).

Bad input files could use comments to specify the expected input error:

``` toml
[input]
versn = 1
#^ Missing 'version' key in 'input' table
```
